# Generated by Django 4.2.23 on 2026-07-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING', 'Booking'), ('CHARGING', 'Charging'), ('PAYMENT', 'Payment'), ('BATTERY', 'Battery'), ('SYSTEM', 'System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
