# Generated by Django 4.2.23 on 2026-07-03 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike')], max_length=10)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('variant', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('battery_capacity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_battery_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('connector_type', models.CharField(choices=[('CCS2', 'CCS2'), ('Type2', 'Type2'), ('GB/T', 'GB/T'), ('CHAdeMO', 'CHAdeMO')], max_length=20)),
                ('efficiency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manufacturing_year', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
