# Generated by Django 6.0 on 2026-07-30 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='availability_is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='booking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='station',
            name='data_quality_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='station',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='external_source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('OPEN_CHARGE_MAP', 'Open Charge Map'), ('IMPORTED', 'Imported')], db_index=True, default='MANUAL', max_length=50),
        ),
        migrations.AddField(
            model_name='station',
            name='external_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='is_locally_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='operator_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='raw_source_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='source_last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'OPERATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='station',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['state', 'city'], name='stations_st_state_135e80_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['external_source', 'external_id'], name='stations_st_externa_f00f04_idx'),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('external_source', 'external_id'), name='unique_external_station'),
        ),
    ]
