# Generated by Django 4.2.23 on 2026-07-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_destination_trip_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(default='Not Set', max_length=200),
            preserve_default=False,
        ),
    ]
