# Generated by Django 6.0 on 2026-07-30 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_options_trip_actual_distance_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100, unique=True)),
                ('seed_value', models.IntegerField(default=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users_created', models.PositiveIntegerField(default=0)),
                ('vehicles_created', models.PositiveIntegerField(default=0)),
                ('trips_created', models.PositiveIntegerField(default=0)),
                ('bookings_created', models.PositiveIntegerField(default=0)),
                ('sessions_created', models.PositiveIntegerField(default=0)),
                ('reviews_created', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SeedGeneratedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100)),
                ('object_id', models.BigIntegerField()),
                ('seed_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_objects', to='trips.seedbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['seed_batch', 'model_label'], name='trips_seedg_seed_ba_554fad_idx')],
            },
        ),
    ]
