# Generated by Django 4.2.30 on 2026-08-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_seedbatch_seedgeneratedobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='suggested_stations_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
