# Generated by Django 4.2.23 on 2026-07-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_name', models.CharField(max_length=50)),
                ('charger_number', models.CharField(max_length=20, unique=True)),
                ('charger_type', models.CharField(choices=[('AC', 'AC'), ('DC', 'DC')], max_length=10)),
                ('connector_type', models.CharField(choices=[('CCS2', 'CCS2'), ('Type2', 'Type2'), ('GB/T', 'GB/T'), ('CHAdeMO', 'CHAdeMO')], max_length=20)),
                ('power_output_kw', models.DecimalField(decimal_places=2, max_digits=6)),
                ('voltage', models.PositiveIntegerField()),
                ('current', models.PositiveIntegerField()),
                ('price_per_kwh', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20)),
                ('installation_date', models.DateField()),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargers', to='stations.station')),
            ],
        ),
    ]
