# Generated by Django 4.2.23 on 2026-07-04 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('charging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('battery_before', models.DecimalField(decimal_places=2, max_digits=5)),
                ('battery_after', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('energy_consumed_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('charging_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('session_status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('INTERRUPTED', 'Interrupted')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charging.charger')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
