# Generated by Django 4.2.18 on 2026-07-31 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('charging', '0002_chargingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to='stations.station'),
        ),
    ]
