# Generated by Django 6.0 on 2026-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0002_chargingsession'),
        ('stations', '0002_station_availability_is_live_station_booking_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charger',
            name='availability_is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charger',
            name='external_connection_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='charger',
            name='raw_connector_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='charger',
            name='source_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charger',
            name='charger_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='charger',
            name='connector_type',
            field=models.CharField(choices=[('CCS2', 'CCS2'), ('Type2', 'Type2'), ('GB/T', 'GB/T'), ('CHAdeMO', 'CHAdeMO'), ('UNKNOWN', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='charger',
            name='current',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charger',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charger',
            name='power_output_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='charger',
            name='price_per_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='charger',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_SERVICE', 'Out of Service'), ('UNKNOWN', 'Unknown')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='charger',
            name='voltage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='charger',
            constraint=models.UniqueConstraint(condition=models.Q(('external_connection_id__isnull', False)), fields=('station', 'external_connection_id'), name='unique_external_connection_per_station'),
        ),
    ]
