# Generated by Django 4.2.30 on 2026-07-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0003_charger_availability_is_live_and_more'),
        ('charging', '0003_chargingsession_station'),
    ]

    operations = [
    ]
