# Generated by Django 4.2.30 on 2026-08-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0004_merge_20260731_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingsession',
            name='station',
        ),
    ]
